//SETORES
export const REQ_SETORES = 'REQ_SETORES';
export const SETORES = 'SETORES';

//MATERIAIS
export const REQ_MATERIAIS = 'REQ_MATERIAIS';
export const MATERIAIS = 'MATERIAIS';
export const REQ_SAVEMATERIAIS = 'REQ_SAVE_MATERIAIS';
export const SAVE_MATERIAIS = 'SAVE_MATERIAIS';
export const REQ_UPDATEMATERIAIS = 'REQ_UPDATEMATERIAIS';
export const UPDATE_MATERIAIS = 'UPDATE_MATERIAIS';
export const REQ_DELETEMATERIAIS = 'REQ_DELETEMATERIAIS';
export const DELETE_MATERIAIS = 'DELETE_MATERIAIS';

export const REQ_SCANNER = 'REQ_SCANNER';
export const SCANNER = 'SCANNER';
