//SETORES
export const REQ_SETORES = 'REQ_SETORES';
export const SETORES = 'SETORES';
export const REQ_CREATE_SETOR = 'REQ_CREATE_SETOR';
export const CREATE_SETOR = 'CREATE_SETOR';
export const REQ_DELETE_SETOR = 'REQ_DELETE_SETOR';
export const DELETE_SETOR = 'DELETE_SETOR';
export const SET_SETOR_ID = 'SET_SETOR_ID';

//MATERIAIS
export const REQ_MATERIAIS = 'REQ_MATERIAIS';
export const MATERIAIS = 'MATERIAIS';
export const REQ_SAVEMATERIAIS = 'REQ_SAVE_MATERIAIS';
export const SAVE_MATERIAIS = 'SAVE_MATERIAIS';
export const REQ_UPDATEMATERIAIS = 'REQ_UPDATEMATERIAIS';
export const UPDATE_MATERIAIS = 'UPDATE_MATERIAIS';
export const REQ_DELETEMATERIAIS = 'REQ_DELETEMATERIAIS';
export const DELETE_MATERIAIS = 'DELETE_MATERIAIS';

export const REQ_SCANNER = 'REQ_SCANNER';
export const SCANNER = 'SCANNER';
